name: Badges

#on:
#  push:
#    branches:
#      - develop

on:
  push:
    branches: [ main ]
  #    path:
  #      - 'auth/**'
  pull_request:
    branches: [ main ]
#    path:
#      - 'auth/**'

jobs:
  update-badges:
    name: Update Badges

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download cloc
        run: sudo apt-get update -y && sudo apt-get install -y cloc
      - name: Get the Numbers
        run: |
          echo "::set-env name=CODE_LINES::$(   ./cloc.sh --loc)"
          echo "::set-env name=COMMENT_LINES::$(./cloc.sh --percentage)%"
      - name: Create Lines-of-Code-Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: f9e802afb7e9ced7e1f5edd115429b74
          filename: dav-express-line-count.json
          label: Lines of Code
          message: ${{ env.CODE_LINES }}
          color: lightgrey
      - name: Create Comments-Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a499ab61d3cc780c30720ffaa66f3dd1
          filename: dav-express-comment-count.json
          label: Comments
          message: ${{ env.COMMENT_LINES }}
          color: green
