name: dav-express

on:
  push:
    branches: [ main ]
  #    path:
  #      - 'auth/**'
  pull_request:
    branches: [ main ]
#    path:
#      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        run: npm install && npm run test:ci
