name: dav-express-test

on:
  push:
    branches: [ main ]
#    path:
#      - 'auth/**'
  pull_request:
    branches: [ main ]
#    path:
#      - 'auth/**'

jobs:
  test:
    name: Tests on different node versions

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2 #optional? investigate
        with:
          node-version: ${{ matrix.node-version }}

      - id: get-node-v-substring
        run: |
          echo ${{matrix.node-version}} | cut -d'.' -f 1
      - run: echo ${{steps.get-node-v-substring.output}}

      - id: get-id
        run: |
          id=$(echo ${{matrix.node-version}} | cut -d'.' -f 1)
          echo "::set-output name=id::$id"
      - run: echo "${{steps.get-id.outputs.id}}"

      - run: npm ci
      - run: npm run test:ci
        env:
          MONGO_URI: '${{secrets.MONGO_URI}}-node-${{steps.get-node-v-substring.output}}'
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
