name: test-coverage

on:
  push:
    branches: [ main ]
  #    path:
  #      - 'auth/**'
  pull_request:
    branches: [ main ]
#    path:
#      - 'auth/**'

jobs:
  test:
    name: Test coverage and the badge

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Updating Test Passing Badge To Failed
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.COVERAGE_BUDGE }}
          gistID: cf394ed0edc2f4dd2f1d692cedd26a77
          filename: dav-express-test-pass-badge.json
          label: Tests
          message: failed
          color: critical

      - name: Setup Node.js environment and Test coverage
        run: npm install && npm run test:cover

      - name: Set node version as variable
        run: echo "NODE_VER_VAR=$(node -v)" >> $GITHUB_ENV

      - name: Console node version variable
        run: echo ${{ env.NODE_VER_VAR }}

      - name: Set lines as var
        run: echo "LINES_VAR=$(git ls-files -- . ':!:.idea' ':!:*.json' ':!:*.md' | xargs cat | wc -l)" >> $GITHUB_ENV

      - name: Console lines var
        run: echo ${{ env.LINES_VAR }}

      - name: Set coverage badge color
        if: env.GH_COVERAGE < 40
        run: echo "GH_COVERAGE_COLOR=red" >> $GITHUB_ENV

      - name: Set coverage badge color
        if: env.GH_COVERAGE >= 40 && env.GH_COVERAGE < 60
        run: echo "GH_COVERAGE_COLOR=orange" >> $GITHUB_ENV

      - name: Set coverage badge color
        if: env.GH_COVERAGE >= 60 && env.GH_COVERAGE < 80
        run: echo "GH_COVERAGE_COLOR=green" >> $GITHUB_ENV

      - name: Set coverage badge color
        if: env.GH_COVERAGE >= 80
        run: echo "GH_COVERAGE_COLOR=blue" >> $GITHUB_ENV

      - name: Updating Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.COVERAGE_BUDGE }}
          gistID: 8538c4d06e5772f17bf3d6ee9f32c211
          filename: dav-express-coverage.json
          label: Coverage
          message: ${{ env.GH_COVERAGE }}%
          color: ${{ env.GH_COVERAGE_COLOR }}

      - name: Updating Test Passing Badge To Passed
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.COVERAGE_BUDGE }}
          gistID: cf394ed0edc2f4dd2f1d692cedd26a77
          filename: dav-express-test-pass-badge.json
          label: Tests
          message: passing
          color: brightgreen
